package jamoliddin.tj.mytest_teachers.domain.util

const val PREFERENCES_NAME = "myTest-preferences"
const val USER_EMAIL = "user_email"
const val USERS = "Users"
const val CATEGORIES = "CATEGORIES"
const val SUBJECTS = "SUBJECTS"
const val SUBJECT_NAME = "subject_name"
const val TEACHERS = "TEACHERS"
const val MATH = "MATH"
const val CHEMISTRY = "CHEMISTRY"
const val PHYSIC = "PHYSIC"
const val INFORMATICS = "INFORMATICS"
const val LEVEL = "LEVEL"
const val MY_QUESTIONS = "MyQuestions"
const val RESULTS_TEST= "ResultsTest"
const val TAG = "myLogs"